# Generated by Django 3.2.5 on 2021-07-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210726_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата размещения'),
        ),
    ]
