# Generated by Django 3.2.5 on 2021-07-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210726_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='comment',
            new_name='description',
        ),
    ]
